repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: detect-private-key
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0  # pick a git hash / tag to point to
  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [ python ]
